{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-json",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ucudajuvjnfd5oc5n3x7udr5s4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.12.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-2.5.0.jar",
          "url": "spring-boot-starter-json-2.5.0.jar",
          "size": 4746,
          "sha512": "d48fa593c59babb503d9f66d827427fe5fc34d2e54f9409f1dbae82ad68ab940cc0d2363f2e3f646bc15fef5949e34b6e98f10c601a2fe4e9224a7b6161656a6",
          "sha256": "2cc6f42483dc43cb0a9ca2c06db069f2309a18e6f4acc07026c10ce04e34d495",
          "sha1": "3823529849c1b848e9623bbccc7c2dc7c3d51f93",
          "md5": "22f5d32aafdba8f8a9d065d32407dfc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.12.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.12.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-2.5.0.jar",
          "url": "spring-boot-starter-json-2.5.0.jar",
          "size": 4746,
          "sha512": "d48fa593c59babb503d9f66d827427fe5fc34d2e54f9409f1dbae82ad68ab940cc0d2363f2e3f646bc15fef5949e34b6e98f10c601a2fe4e9224a7b6161656a6",
          "sha256": "2cc6f42483dc43cb0a9ca2c06db069f2309a18e6f4acc07026c10ce04e34d495",
          "sha1": "3823529849c1b848e9623bbccc7c2dc7c3d51f93",
          "md5": "22f5d32aafdba8f8a9d065d32407dfc4"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-2.5.0.jar",
          "url": "spring-boot-starter-json-2.5.0.jar",
          "size": 4746,
          "sha512": "d48fa593c59babb503d9f66d827427fe5fc34d2e54f9409f1dbae82ad68ab940cc0d2363f2e3f646bc15fef5949e34b6e98f10c601a2fe4e9224a7b6161656a6",
          "sha256": "2cc6f42483dc43cb0a9ca2c06db069f2309a18e6f4acc07026c10ce04e34d495",
          "sha1": "3823529849c1b848e9623bbccc7c2dc7c3d51f93",
          "md5": "22f5d32aafdba8f8a9d065d32407dfc4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "2.5.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-2.5.0.jar",
          "url": "spring-boot-starter-json-2.5.0.jar",
          "size": 4746,
          "sha512": "d48fa593c59babb503d9f66d827427fe5fc34d2e54f9409f1dbae82ad68ab940cc0d2363f2e3f646bc15fef5949e34b6e98f10c601a2fe4e9224a7b6161656a6",
          "sha256": "2cc6f42483dc43cb0a9ca2c06db069f2309a18e6f4acc07026c10ce04e34d495",
          "sha1": "3823529849c1b848e9623bbccc7c2dc7c3d51f93",
          "md5": "22f5d32aafdba8f8a9d065d32407dfc4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "2.5.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-2.5.0-javadoc.jar",
          "url": "spring-boot-starter-json-2.5.0-javadoc.jar",
          "size": 4744,
          "sha512": "fbbb9bbaafa53f8830e579c1ab8b0cb5bf1416973813c703e550bd788ab04eb173198699ea7f9e7e9660e8a2fa34f2afdb02069b94e00ff256b46071e88f1f5b",
          "sha256": "81836db146bb7a08a93c1ab71aa526fd841fdd19405927e07c822cd2d547cb2a",
          "sha1": "b2be451b5ac09c63ae78c1e04b3833f68587d2f7",
          "md5": "c6f8f1e15d152e1e0e21be4b9caaf337"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-2.5.0-sources.jar",
          "url": "spring-boot-starter-json-2.5.0-sources.jar",
          "size": 4741,
          "sha512": "7ec5ec5d80d0bafccf63081c57d5074849699901b8aaf45646e40a3ae4a6a815dbfee371180e728e5ec5030cfdf0727b257b1b1790f9d80b270353154b05fb10",
          "sha256": "fe0558cb74d1a5bb422f0ac27af74841aebfe4e7d0354d9d139062acf1399262",
          "sha1": "f668a34b60fb430deae04f8a4a005858aee0fc2c",
          "md5": "686a3552eefde7776681510b9070dcb3"
        }
      ]
    }
  ]
}
