{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context",
    "version": "5.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "imbym54z4rgzrmhomxpq7qqw3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-5.3.7.jar",
          "url": "spring-context-5.3.7.jar",
          "size": 1249987,
          "sha512": "320f03fbb0f8e80d2c0303854e5b01deefd53f0f3ba520ab2db8c9cbb47508c279ef549e0aae79951ac458e900e32cb9a44d343b9f7615d9aa9bae6a6d028898",
          "sha256": "6d9bb2dcc297f3eb5c5457cfe2159935ad7d77a2400c8252e4beb235c1168b9f",
          "sha1": "330b3957efdcdebe3550b8e2c5d45a4c25496626",
          "md5": "f64caaee7fb1b1101faa7705c8e49b36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-5.3.7.jar",
          "url": "spring-context-5.3.7.jar",
          "size": 1249987,
          "sha512": "320f03fbb0f8e80d2c0303854e5b01deefd53f0f3ba520ab2db8c9cbb47508c279ef549e0aae79951ac458e900e32cb9a44d343b9f7615d9aa9bae6a6d028898",
          "sha256": "6d9bb2dcc297f3eb5c5457cfe2159935ad7d77a2400c8252e4beb235c1168b9f",
          "sha1": "330b3957efdcdebe3550b8e2c5d45a4c25496626",
          "md5": "f64caaee7fb1b1101faa7705c8e49b36"
        }
      ]
    }
  ]
}
