{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ucudajuvjnfd5oc5n3x7udr5s4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.46"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.46"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.46"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.0.jar",
          "url": "spring-boot-starter-tomcat-2.5.0.jar",
          "size": 4796,
          "sha512": "3c2602bfc5149aa289d453ce2fafbefc34960a81af4b1b0b4260d70d6929af0eab8835857f32c6b9f5fa2477d7d0204e0cb01312cd2d46fba3b81b08a39c5871",
          "sha256": "8f365217f028ce7afade295992c1a21f2644c632020039a3850a6e65ee3a4e1a",
          "sha1": "3b93aeb708d3319522fb21409ec314ad4d2ef9b3",
          "md5": "f3dc3e286739ef27c5df4d1b1d816693"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.46"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.46"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.46"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.0.jar",
          "url": "spring-boot-starter-tomcat-2.5.0.jar",
          "size": 4796,
          "sha512": "3c2602bfc5149aa289d453ce2fafbefc34960a81af4b1b0b4260d70d6929af0eab8835857f32c6b9f5fa2477d7d0204e0cb01312cd2d46fba3b81b08a39c5871",
          "sha256": "8f365217f028ce7afade295992c1a21f2644c632020039a3850a6e65ee3a4e1a",
          "sha1": "3b93aeb708d3319522fb21409ec314ad4d2ef9b3",
          "md5": "f3dc3e286739ef27c5df4d1b1d816693"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.0.jar",
          "url": "spring-boot-starter-tomcat-2.5.0.jar",
          "size": 4796,
          "sha512": "3c2602bfc5149aa289d453ce2fafbefc34960a81af4b1b0b4260d70d6929af0eab8835857f32c6b9f5fa2477d7d0204e0cb01312cd2d46fba3b81b08a39c5871",
          "sha256": "8f365217f028ce7afade295992c1a21f2644c632020039a3850a6e65ee3a4e1a",
          "sha1": "3b93aeb708d3319522fb21409ec314ad4d2ef9b3",
          "md5": "f3dc3e286739ef27c5df4d1b1d816693"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.5.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.0.jar",
          "url": "spring-boot-starter-tomcat-2.5.0.jar",
          "size": 4796,
          "sha512": "3c2602bfc5149aa289d453ce2fafbefc34960a81af4b1b0b4260d70d6929af0eab8835857f32c6b9f5fa2477d7d0204e0cb01312cd2d46fba3b81b08a39c5871",
          "sha256": "8f365217f028ce7afade295992c1a21f2644c632020039a3850a6e65ee3a4e1a",
          "sha1": "3b93aeb708d3319522fb21409ec314ad4d2ef9b3",
          "md5": "f3dc3e286739ef27c5df4d1b1d816693"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.5.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.0-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.5.0-javadoc.jar",
          "size": 4744,
          "sha512": "b841a2764a7068cd70ade655f7fb99e3530aa6b05109bc39ca8d97397218c82c0527235d4ce9111aab9676cd83a16d2421c9b58d574865bea99bf0071f196cb7",
          "sha256": "8b18e5b14e8c6983db08c284364ee3b5ff380c2791d06ea233b8c3794c821282",
          "sha1": "ad9b8b6f47e02d6ce14f6c99dddc56f7758fd75c",
          "md5": "c3d1ddfed56ca4e0cb52a535d76eee0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.5.0-sources.jar",
          "url": "spring-boot-starter-tomcat-2.5.0-sources.jar",
          "size": 4742,
          "sha512": "089069038a5dbc5261d8a8fdb92933af1b453c5bce9331220fb418ad34a4732d9b37caabeb1f4c0cd39434bfe9d8df5ca60923d929da0c3afc8fc6e31cb5ba85",
          "sha256": "4e2ea6817e2fc21a1988bab37087c9cc19d1c2021eeda9d02861e02940b04020",
          "sha1": "85ee7cdae4cfbcbeda0e3cdccf828b4579bbaa57",
          "md5": "c40bf15295ec15b78cdc1d147e5706a2"
        }
      ]
    }
  ]
}
