{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ucudajuvjnfd5oc5n3x7udr5s4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-2.5.0.jar",
          "url": "spring-boot-starter-web-2.5.0.jar",
          "size": 4805,
          "sha512": "64c82a2dd5ca6ef587b538267a33d36c83551fd435425188f45b6cc0428849ebc0086a283293a519372b5c123447a6f61fe60b1e01b892a344fdfa1f1954a636",
          "sha256": "aaed6b244c55e14efc9abfb15c7e2ba0874c88c37b830911f87b9f06e9f2b9de",
          "sha1": "3103486844ed786b6ba420971ad137658a2da803",
          "md5": "415b65ab680e8c31ec360cee329e9f04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-2.5.0.jar",
          "url": "spring-boot-starter-web-2.5.0.jar",
          "size": 4805,
          "sha512": "64c82a2dd5ca6ef587b538267a33d36c83551fd435425188f45b6cc0428849ebc0086a283293a519372b5c123447a6f61fe60b1e01b892a344fdfa1f1954a636",
          "sha256": "aaed6b244c55e14efc9abfb15c7e2ba0874c88c37b830911f87b9f06e9f2b9de",
          "sha1": "3103486844ed786b6ba420971ad137658a2da803",
          "md5": "415b65ab680e8c31ec360cee329e9f04"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.5.0.jar",
          "url": "spring-boot-starter-web-2.5.0.jar",
          "size": 4805,
          "sha512": "64c82a2dd5ca6ef587b538267a33d36c83551fd435425188f45b6cc0428849ebc0086a283293a519372b5c123447a6f61fe60b1e01b892a344fdfa1f1954a636",
          "sha256": "aaed6b244c55e14efc9abfb15c7e2ba0874c88c37b830911f87b9f06e9f2b9de",
          "sha1": "3103486844ed786b6ba420971ad137658a2da803",
          "md5": "415b65ab680e8c31ec360cee329e9f04"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "2.5.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.5.0.jar",
          "url": "spring-boot-starter-web-2.5.0.jar",
          "size": 4805,
          "sha512": "64c82a2dd5ca6ef587b538267a33d36c83551fd435425188f45b6cc0428849ebc0086a283293a519372b5c123447a6f61fe60b1e01b892a344fdfa1f1954a636",
          "sha256": "aaed6b244c55e14efc9abfb15c7e2ba0874c88c37b830911f87b9f06e9f2b9de",
          "sha1": "3103486844ed786b6ba420971ad137658a2da803",
          "md5": "415b65ab680e8c31ec360cee329e9f04"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "2.5.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.5.0-javadoc.jar",
          "url": "spring-boot-starter-web-2.5.0-javadoc.jar",
          "size": 4743,
          "sha512": "a586b5ff7f8997e53120b9315bdd2e92b04751535abb77765d5fc96158337e73314151ab231e295665ed3d8b951cefb4b1e309b41105be53caa508a2b0240355",
          "sha256": "8697fc42891cfbdca8b60c9d7d6ad79abee1f081a3afb59ff74b87a24a65a8c7",
          "sha1": "db92699e249f7a0b6f2eae41a5517eff01336298",
          "md5": "127b1122356665c73a304eb94a4f5246"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-2.5.0-sources.jar",
          "url": "spring-boot-starter-web-2.5.0-sources.jar",
          "size": 4741,
          "sha512": "6c3e0dd9f4879ca8c0e66a327097117f777b9303d9326b9407c7740158c871f5c80bead873ddefe27a16f3f69fe0a44294db86ff8a746ec5ec84e1688ad8e016",
          "sha256": "cf66886ce815851225a03a002e8b2e99ef9962a455d85995e439c64a0842d82d",
          "sha1": "8e76531b39a53c39955b0b77c71ea7c4c047ca1c",
          "md5": "7488ddb6df9b53aecd1873059f4dfc29"
        }
      ]
    }
  ]
}
