{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ucudajuvjnfd5oc5n3x7udr5s4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-2.5.0.jar",
          "url": "spring-boot-test-2.5.0.jar",
          "size": 219101,
          "sha512": "bd32cf6032b65101e33d354db3f1a5d3bbc761b681ce2173334d5bf17c7469f8e9bd5af73c7ee4c493b2fc113276741f24adfd97885e435790ad7c5807c78eeb",
          "sha256": "386a8753dc18cda0c397daa7f0b7c5164b952e4498dca1f3b97af798227ca8a9",
          "sha1": "53ecfc751fd08d6dab2301c06e8e3de74d85185a",
          "md5": "d855e3b93cf00a64ea73418f084229b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-2.5.0.jar",
          "url": "spring-boot-test-2.5.0.jar",
          "size": 219101,
          "sha512": "bd32cf6032b65101e33d354db3f1a5d3bbc761b681ce2173334d5bf17c7469f8e9bd5af73c7ee4c493b2fc113276741f24adfd97885e435790ad7c5807c78eeb",
          "sha256": "386a8753dc18cda0c397daa7f0b7c5164b952e4498dca1f3b97af798227ca8a9",
          "sha1": "53ecfc751fd08d6dab2301c06e8e3de74d85185a",
          "md5": "d855e3b93cf00a64ea73418f084229b8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-2.5.0-javadoc.jar",
          "url": "spring-boot-test-2.5.0-javadoc.jar",
          "size": 317211,
          "sha512": "4de7e4d3815ce4bc056e96fec8a0e14f9a7d0a129143566db1db5c1b4e32e18698f434000d4e477c3cbccebfce429955d52b2cea0a37ca86eee86d4e1d164004",
          "sha256": "dc18f964b895347deecd8074057ad08be3723d4c66677f21ae707a13bc35f88c",
          "sha1": "c98a77e4c574accbf73fab1ee56fdc7657a40c38",
          "md5": "7c7836b80afad90f5f0403a3e47d94f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-2.5.0-sources.jar",
          "url": "spring-boot-test-2.5.0-sources.jar",
          "size": 153319,
          "sha512": "b0115b611bdb6040ceb04485b2849776ceb4aba6ae17f672ddf07f761209a3df83fdba79e68e9ca6d31115a2bd932d3759f6d9f7efbaa6b490ae5414b0a28280",
          "sha256": "6612b49a305cb1f3fe8a8ff7706eb7a3b8bf9e310aa9bf5b581cff51190b3be8",
          "sha1": "4920bda763ec364c309ec97aaea361d0f93c882e",
          "md5": "135c966babe00a103e076e5b91cbcd93"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-test-2.5.0.jar",
          "url": "spring-boot-test-2.5.0.jar",
          "size": 219101,
          "sha512": "bd32cf6032b65101e33d354db3f1a5d3bbc761b681ce2173334d5bf17c7469f8e9bd5af73c7ee4c493b2fc113276741f24adfd97885e435790ad7c5807c78eeb",
          "sha256": "386a8753dc18cda0c397daa7f0b7c5164b952e4498dca1f3b97af798227ca8a9",
          "sha1": "53ecfc751fd08d6dab2301c06e8e3de74d85185a",
          "md5": "d855e3b93cf00a64ea73418f084229b8"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "2.5.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-2.5.0.jar",
          "url": "spring-boot-test-2.5.0.jar",
          "size": 219101,
          "sha512": "bd32cf6032b65101e33d354db3f1a5d3bbc761b681ce2173334d5bf17c7469f8e9bd5af73c7ee4c493b2fc113276741f24adfd97885e435790ad7c5807c78eeb",
          "sha256": "386a8753dc18cda0c397daa7f0b7c5164b952e4498dca1f3b97af798227ca8a9",
          "sha1": "53ecfc751fd08d6dab2301c06e8e3de74d85185a",
          "md5": "d855e3b93cf00a64ea73418f084229b8"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "2.5.0"
        }
      ]
    }
  ]
}
