{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-beans",
    "version": "5.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "imbym54z4rgzrmhomxpq7qqw3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-5.3.7.jar",
          "url": "spring-beans-5.3.7.jar",
          "size": 696458,
          "sha512": "2512f6f69062cdb132dd5cb5ca4ca74f09ae89b3fc5018393b6defe62c50ba26f47526d27af685f4cc9c6047d052244ece436ef7ad01a09503e24fb2fb7fd0f0",
          "sha256": "8c02823ceb0370bcf6e9eeccbc2d429a484b429457faa7e8bc39506eaaf6ace6",
          "sha1": "8b1eacd7aaa12f7d173a2f0836d28bd0c1b098fe",
          "md5": "833fb3aa90fd443789b6af5e5eb132b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-5.3.7.jar",
          "url": "spring-beans-5.3.7.jar",
          "size": 696458,
          "sha512": "2512f6f69062cdb132dd5cb5ca4ca74f09ae89b3fc5018393b6defe62c50ba26f47526d27af685f4cc9c6047d052244ece436ef7ad01a09503e24fb2fb7fd0f0",
          "sha256": "8c02823ceb0370bcf6e9eeccbc2d429a484b429457faa7e8bc39506eaaf6ace6",
          "sha1": "8b1eacd7aaa12f7d173a2f0836d28bd0c1b098fe",
          "md5": "833fb3aa90fd443789b6af5e5eb132b2"
        }
      ]
    }
  ]
}
