{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "5.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "imbym54z4rgzrmhomxpq7qqw3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.7"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.7.jar",
          "url": "spring-test-5.3.7.jar",
          "size": 766187,
          "sha512": "8c54f8c715db3d82500f4a51d64bbd073d79adcfbb3300ad70ffaa1c37df6c13e668686fac5f90c8d44d7c7b8e7c64854977a22e0c93cb66abaa4f77cc33c854",
          "sha256": "024e1cf900bab6fc9bb103ad000f6f7742bc01d447fa8d633418b56aeb7ca61d",
          "sha1": "e23e2a03e95237c48b0db4f399099cc9eac1480c",
          "md5": "6e17fd14cb4bf69ac32bee2b5ddb7b32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.7"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.7.jar",
          "url": "spring-test-5.3.7.jar",
          "size": 766187,
          "sha512": "8c54f8c715db3d82500f4a51d64bbd073d79adcfbb3300ad70ffaa1c37df6c13e668686fac5f90c8d44d7c7b8e7c64854977a22e0c93cb66abaa4f77cc33c854",
          "sha256": "024e1cf900bab6fc9bb103ad000f6f7742bc01d447fa8d633418b56aeb7ca61d",
          "sha1": "e23e2a03e95237c48b0db4f399099cc9eac1480c",
          "md5": "6e17fd14cb4bf69ac32bee2b5ddb7b32"
        }
      ]
    }
  ]
}
