{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jsr310",
    "version": "2.12.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.12.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.3"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.12.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.12.3.jar",
          "url": "jackson-datatype-jsr310-2.12.3.jar",
          "size": 119252,
          "sha512": "765d250e727be97a73bebb55741302fe05121980a82aa1ec446fc08ad62771a075093247ec32d5847a4bd9414dbee402fab9e2d2d8b049611b979fb6d45f5852",
          "sha256": "6d7d004dd6ba71caa3b5445398a32e9b45e806f05fb487b4fc2bbb468af4f421",
          "sha1": "61181b2cae45aba6632249729f5e28a58bfede13",
          "md5": "bf7dbeae9f0a653b8fc3c5e05484a42b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.12.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.3"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.12.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.12.3.jar",
          "url": "jackson-datatype-jsr310-2.12.3.jar",
          "size": 119252,
          "sha512": "765d250e727be97a73bebb55741302fe05121980a82aa1ec446fc08ad62771a075093247ec32d5847a4bd9414dbee402fab9e2d2d8b049611b979fb6d45f5852",
          "sha256": "6d7d004dd6ba71caa3b5445398a32e9b45e806f05fb487b4fc2bbb468af4f421",
          "sha1": "61181b2cae45aba6632249729f5e28a58bfede13",
          "md5": "bf7dbeae9f0a653b8fc3c5e05484a42b"
        }
      ]
    }
  ]
}
