{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-autoconfigure",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ucudajuvjnfd5oc5n3x7udr5s4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.5.0.jar",
          "url": "spring-boot-autoconfigure-2.5.0.jar",
          "size": 1559010,
          "sha512": "9afa3975bc1acef103ff1c592c21b561465acfcb1786ac8d237e5b0f8b93a0e914fbdeb54c3e9cf4ee3e2ac2db7839643e24182af76f50a68a2942ca389540ee",
          "sha256": "291adbe58b6ed20ddb788bfd62fbb4a43af7c55be38d1233714f5954ffe9142a",
          "sha1": "64c7bbc941c70895621ed613f38dc66b73ea9341",
          "md5": "4536900c1ead8817e84dbafd18683f88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.5.0.jar",
          "url": "spring-boot-autoconfigure-2.5.0.jar",
          "size": 1559010,
          "sha512": "9afa3975bc1acef103ff1c592c21b561465acfcb1786ac8d237e5b0f8b93a0e914fbdeb54c3e9cf4ee3e2ac2db7839643e24182af76f50a68a2942ca389540ee",
          "sha256": "291adbe58b6ed20ddb788bfd62fbb4a43af7c55be38d1233714f5954ffe9142a",
          "sha1": "64c7bbc941c70895621ed613f38dc66b73ea9341",
          "md5": "4536900c1ead8817e84dbafd18683f88"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.5.0.jar",
          "url": "spring-boot-autoconfigure-2.5.0.jar",
          "size": 1559010,
          "sha512": "9afa3975bc1acef103ff1c592c21b561465acfcb1786ac8d237e5b0f8b93a0e914fbdeb54c3e9cf4ee3e2ac2db7839643e24182af76f50a68a2942ca389540ee",
          "sha256": "291adbe58b6ed20ddb788bfd62fbb4a43af7c55be38d1233714f5954ffe9142a",
          "sha1": "64c7bbc941c70895621ed613f38dc66b73ea9341",
          "md5": "4536900c1ead8817e84dbafd18683f88"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-autoconfigure-maven-optional",
          "version": "2.5.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.5.0.jar",
          "url": "spring-boot-autoconfigure-2.5.0.jar",
          "size": 1559010,
          "sha512": "9afa3975bc1acef103ff1c592c21b561465acfcb1786ac8d237e5b0f8b93a0e914fbdeb54c3e9cf4ee3e2ac2db7839643e24182af76f50a68a2942ca389540ee",
          "sha256": "291adbe58b6ed20ddb788bfd62fbb4a43af7c55be38d1233714f5954ffe9142a",
          "sha1": "64c7bbc941c70895621ed613f38dc66b73ea9341",
          "md5": "4536900c1ead8817e84dbafd18683f88"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-autoconfigure-maven-optional",
          "version": "2.5.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.5.0-javadoc.jar",
          "url": "spring-boot-autoconfigure-2.5.0-javadoc.jar",
          "size": 2388445,
          "sha512": "d11a910daddfd29c451259b3fdc162a9fb805d043575e7ac1223fa92a07d221ce726b3c6cd1c51b75cdec2e5102c102081d6dd13730341c3d0af487cb06fa4f6",
          "sha256": "f9d0075dbedcfedb223b3e41054f82194677ed0247ca023709e8e778daf9e62a",
          "sha1": "20aabf3dcc6fbf47b3f8f9e7d20abedda0f4f839",
          "md5": "49a18681c6411e9c5d7fa3f184f4add0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-2.5.0-sources.jar",
          "url": "spring-boot-autoconfigure-2.5.0-sources.jar",
          "size": 933310,
          "sha512": "95c2290f52e51c3699c43f2cd1c0c9e597337cf3f5d5866d1f291aafe25a5ffae093fd116af6a861929e9d5aece83b81ea208b177f12663810245d0c7ad96edb",
          "sha256": "70a3467927bb9137e4974e67fb95cf2c250809b38246967b135aaaa96b87b951",
          "sha1": "56361cf7592e27bacb689767be065db6e31ca95e",
          "md5": "292396ee5d9c7a219a8d4e4534a1ec04"
        }
      ]
    }
  ]
}
