{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "5.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "imbym54z4rgzrmhomxpq7qqw3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.7"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.7"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.7.jar",
          "url": "spring-web-5.3.7.jar",
          "size": 1595716,
          "sha512": "3f4468099d14de9bf6db1919755a1ac3da4d9bc7bbbe8d7405f255b01e5ce5d8afd5af2a7cff5abd8e1237951f95a14c6045f13d5ebe5dc2f196018c7267c21c",
          "sha256": "bba996b82aaec5d896d9cd05e33525acabd263042d47486fbe2609d144e906a0",
          "sha1": "49e6a8f45e77f14ef16f82c0413254ef493b785f",
          "md5": "2dc93a914f5ab83682971dc708e9c59f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.7"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.7"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.7.jar",
          "url": "spring-web-5.3.7.jar",
          "size": 1595716,
          "sha512": "3f4468099d14de9bf6db1919755a1ac3da4d9bc7bbbe8d7405f255b01e5ce5d8afd5af2a7cff5abd8e1237951f95a14c6045f13d5ebe5dc2f196018c7267c21c",
          "sha256": "bba996b82aaec5d896d9cd05e33525acabd263042d47486fbe2609d144e906a0",
          "sha1": "49e6a8f45e77f14ef16f82c0413254ef493b785f",
          "md5": "2dc93a914f5ab83682971dc708e9c59f"
        }
      ]
    }
  ]
}
