{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ucudajuvjnfd5oc5n3x7udr5s4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.7"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.28"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.5.0.jar",
          "url": "spring-boot-starter-2.5.0.jar",
          "size": 4770,
          "sha512": "114242e82e00631e76b90368a8d3306e5886351dfa6643f8ef7458067a3b0f86cbb9850675944f48a795ff11f4f2f719f2c4e19986f592331630b14ae22d4e38",
          "sha256": "8e3241279f2db715d4051b1da1f36c42b70a4eb50b4ebbd7e935855a5c2cbfbd",
          "sha1": "a910887c01efcc7d12f3f89a7604d436f26eeb90",
          "md5": "a05a7b1382b90abb6578b5dfc128f58a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.7"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.28"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.5.0.jar",
          "url": "spring-boot-starter-2.5.0.jar",
          "size": 4770,
          "sha512": "114242e82e00631e76b90368a8d3306e5886351dfa6643f8ef7458067a3b0f86cbb9850675944f48a795ff11f4f2f719f2c4e19986f592331630b14ae22d4e38",
          "sha256": "8e3241279f2db715d4051b1da1f36c42b70a4eb50b4ebbd7e935855a5c2cbfbd",
          "sha1": "a910887c01efcc7d12f3f89a7604d436f26eeb90",
          "md5": "a05a7b1382b90abb6578b5dfc128f58a"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.5.0.jar",
          "url": "spring-boot-starter-2.5.0.jar",
          "size": 4770,
          "sha512": "114242e82e00631e76b90368a8d3306e5886351dfa6643f8ef7458067a3b0f86cbb9850675944f48a795ff11f4f2f719f2c4e19986f592331630b14ae22d4e38",
          "sha256": "8e3241279f2db715d4051b1da1f36c42b70a4eb50b4ebbd7e935855a5c2cbfbd",
          "sha1": "a910887c01efcc7d12f3f89a7604d436f26eeb90",
          "md5": "a05a7b1382b90abb6578b5dfc128f58a"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.5.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.5.0.jar",
          "url": "spring-boot-starter-2.5.0.jar",
          "size": 4770,
          "sha512": "114242e82e00631e76b90368a8d3306e5886351dfa6643f8ef7458067a3b0f86cbb9850675944f48a795ff11f4f2f719f2c4e19986f592331630b14ae22d4e38",
          "sha256": "8e3241279f2db715d4051b1da1f36c42b70a4eb50b4ebbd7e935855a5c2cbfbd",
          "sha1": "a910887c01efcc7d12f3f89a7604d436f26eeb90",
          "md5": "a05a7b1382b90abb6578b5dfc128f58a"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.5.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.5.0-javadoc.jar",
          "url": "spring-boot-starter-2.5.0-javadoc.jar",
          "size": 4738,
          "sha512": "8c64280ac44bb99eae44fe512fa1ac5b569e1b1f0410eaef7ccc52dcfb39786c3ab0fc0b58d7e9f87c6e43338579468ffa4957e38a632159e52a088b4ec3d3ec",
          "sha256": "664e111b097ba865c8949b0a25c8473c6048798e5bc49bd8cbe98308cea4c43f",
          "sha1": "c6ce60c5a780c603d59aab37c506f1336ac27c7f",
          "md5": "6916e02be9abd72c15c8ef0d658ab8b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.5.0-sources.jar",
          "url": "spring-boot-starter-2.5.0-sources.jar",
          "size": 4736,
          "sha512": "0855c3d328e060382641bd65e431137b1e94f4a998a2c2b7e8011715ff806725adf3aa3817d171e56645f8072431b4a1512e6abfcaa592871f52908de6616466",
          "sha256": "db68c7e870894321cf907a8c1cba9cd648728212cb0a3a9c3a5a24a9342564d9",
          "sha1": "7371745bda73bf6fd2c778d7b29bf836a5bb966a",
          "md5": "edff98a2860eee1520bc2169618e6b08"
        }
      ]
    }
  ]
}
