{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ucudajuvjnfd5oc5n3x7udr5s4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-2.5.0.jar",
          "url": "spring-boot-starter-logging-2.5.0.jar",
          "size": 4760,
          "sha512": "75178daf1deba8ab39f9aa5f488d57d499182e7cad3e22f4034933010b17e7625b9a51fc7d55b0d2a594007a900d374a532741a309548a9da48854168ab3fd94",
          "sha256": "1e32f799e56feb3ff9d67407e4b58b10b21bdb84da07bb5da93a88eb8b47be00",
          "sha1": "22401482ba1c5a1dcd3d33e47295779211b913d8",
          "md5": "247e3ce630b1e710e3ea53a64a5b77fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-2.5.0.jar",
          "url": "spring-boot-starter-logging-2.5.0.jar",
          "size": 4760,
          "sha512": "75178daf1deba8ab39f9aa5f488d57d499182e7cad3e22f4034933010b17e7625b9a51fc7d55b0d2a594007a900d374a532741a309548a9da48854168ab3fd94",
          "sha256": "1e32f799e56feb3ff9d67407e4b58b10b21bdb84da07bb5da93a88eb8b47be00",
          "sha1": "22401482ba1c5a1dcd3d33e47295779211b913d8",
          "md5": "247e3ce630b1e710e3ea53a64a5b77fc"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-2.5.0.jar",
          "url": "spring-boot-starter-logging-2.5.0.jar",
          "size": 4760,
          "sha512": "75178daf1deba8ab39f9aa5f488d57d499182e7cad3e22f4034933010b17e7625b9a51fc7d55b0d2a594007a900d374a532741a309548a9da48854168ab3fd94",
          "sha256": "1e32f799e56feb3ff9d67407e4b58b10b21bdb84da07bb5da93a88eb8b47be00",
          "sha1": "22401482ba1c5a1dcd3d33e47295779211b913d8",
          "md5": "247e3ce630b1e710e3ea53a64a5b77fc"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-logging-maven-optional",
          "version": "2.5.0"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-2.5.0.jar",
          "url": "spring-boot-starter-logging-2.5.0.jar",
          "size": 4760,
          "sha512": "75178daf1deba8ab39f9aa5f488d57d499182e7cad3e22f4034933010b17e7625b9a51fc7d55b0d2a594007a900d374a532741a309548a9da48854168ab3fd94",
          "sha256": "1e32f799e56feb3ff9d67407e4b58b10b21bdb84da07bb5da93a88eb8b47be00",
          "sha1": "22401482ba1c5a1dcd3d33e47295779211b913d8",
          "md5": "247e3ce630b1e710e3ea53a64a5b77fc"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-logging-maven-optional",
          "version": "2.5.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-2.5.0-javadoc.jar",
          "url": "spring-boot-starter-logging-2.5.0-javadoc.jar",
          "size": 4745,
          "sha512": "560ec0af9d8fbeda87468b4e970b926334dd25f7cf85b85c4cd75c7a15481a326fba54a726196a8172f9f147d0e82bd6ba9476f4e2321bc7bc02e11eaf684149",
          "sha256": "6c4d8ba83af2fb2d54850c1705c38cb4be3b0493483d93223a1061c756060c82",
          "sha1": "22e50570dc1fa6909e3864f4ca51644d08925786",
          "md5": "f76883c3be9909fe6df21f79c128ef0c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-2.5.0-sources.jar",
          "url": "spring-boot-starter-logging-2.5.0-sources.jar",
          "size": 4744,
          "sha512": "321de63fc3aada518b98324c603d148568e83eea25053f2c3cb7c65d070eb8bb1b1fb2e88691e5c41ccf0e44b2c9cbce82ccdf1575923736dcc5036999aff780",
          "sha256": "711c0d5c777f0524a0895620b8b8d90bb1881e5bc60de610e2ff83ebee0f4b45",
          "sha1": "ebb883b6eb763af2d021e191e3bc1d820d28aa76",
          "md5": "39379ec80ebb1599c6a6bcca8819fc05"
        }
      ]
    }
  ]
}
