{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-expression",
    "version": "5.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "imbym54z4rgzrmhomxpq7qqw3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-5.3.7.jar",
          "url": "spring-expression-5.3.7.jar",
          "size": 282647,
          "sha512": "569ef33211edec42b75c5c3f1d18f0ca3a9f2ab054f6217854a6cd13a1a0ae42424c9f4bf77fbe3445e998c6fb6373f1f567fb111372bc65e501768ce2606bbd",
          "sha256": "a818630d8e55077f2be7254f9dc03be1b7d01143f7c36f8cdcfc9c7be0b94573",
          "sha1": "13351fce0a604957cd6a41478ebb54a953a0245e",
          "md5": "a7f7a73ab8888a88e2bdc6b90c04d4d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-5.3.7.jar",
          "url": "spring-expression-5.3.7.jar",
          "size": 282647,
          "sha512": "569ef33211edec42b75c5c3f1d18f0ca3a9f2ab054f6217854a6cd13a1a0ae42424c9f4bf77fbe3445e998c6fb6373f1f567fb111372bc65e501768ce2606bbd",
          "sha256": "a818630d8e55077f2be7254f9dc03be1b7d01143f7c36f8cdcfc9c7be0b94573",
          "sha1": "13351fce0a604957cd6a41478ebb54a953a0245e",
          "md5": "a7f7a73ab8888a88e2bdc6b90c04d4d5"
        }
      ]
    }
  ]
}
